<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <AvaloniaVersion>11.2.3</AvaloniaVersion>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <Import Project="..\Version.props" />
</Project>
